steps:
  # 1. Compilar la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/caelum/caelum:$COMMIT_SHA', '.']

  # 2. Subir la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/caelum/caelum:$COMMIT_SHA']

  # 3. Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'caelum'
      - '--image=europe-southwest1-docker.pkg.dev/$PROJECT_ID/caelum/caelum:$COMMIT_SHA'
      - '--region=europe-southwest1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/caelum/caelum:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
